name: run-cypress-tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run Cypress tests
      run: npm run executeAllTests:report
      env: 
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress
        path: /home/runner/work/cypress-with-vr-html-report/cypress-with-vr-html-report/cypress/
        retention-days: 30
    - name: Send message to Slack API
      uses: archive/github-actions-slack@v2.0.0
      id: notify
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        slack-channel: C05KERQEWAX
        slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}" 🤓
    - name: Result from Send Message
      run: echo "The result was ${{ steps.notify.outputs.slack-result }}"        
